apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx

spec:
  rules:
    - host: {{ .Values.app.host }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}
              servicePort: {{ .Values.app.container.port }}
            path: {{ .Values.app.path }}
