apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.app.container.port }}
    targetPort: {{ .Values.app.container.port }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}
